// tg-proxy plugin protocol, v1.
//
// External scanners and redactors run as subprocesses spawned by tg-proxy
// via hashicorp/go-plugin and communicate over gRPC. This file is the
// single source of truth for what either side puts on the wire; the
// generated *.pb.go files alongside this proto, and the Python stubs under
// packaging/python-sdk-plugin/, are built from this one definition.
//
// Regenerate with:
//   make proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.0
// source: plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Scanner_Info_FullMethodName = "/tgproxy.plugin.v1.Scanner/Info"
	Scanner_Scan_FullMethodName = "/tgproxy.plugin.v1.Scanner/Scan"
)

// ScannerClient is the client API for Scanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Scanner is the service implemented by external scanner plugins.
type ScannerClient interface {
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error)
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
}

type scannerClient struct {
	cc grpc.ClientConnInterface
}

func NewScannerClient(cc grpc.ClientConnInterface) ScannerClient {
	return &scannerClient{cc}
}

func (c *scannerClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, Scanner_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, Scanner_Scan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScannerServer is the server API for Scanner service.
// All implementations must embed UnimplementedScannerServer
// for forward compatibility.
//
// Scanner is the service implemented by external scanner plugins.
type ScannerServer interface {
	Info(context.Context, *Empty) (*PluginInfo, error)
	Scan(context.Context, *ScanRequest) (*ScanResponse, error)
	mustEmbedUnimplementedScannerServer()
}

// UnimplementedScannerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScannerServer struct{}

func (UnimplementedScannerServer) Info(context.Context, *Empty) (*PluginInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedScannerServer) Scan(context.Context, *ScanRequest) (*ScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedScannerServer) mustEmbedUnimplementedScannerServer() {}
func (UnimplementedScannerServer) testEmbeddedByValue()                 {}

// UnsafeScannerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScannerServer will
// result in compilation errors.
type UnsafeScannerServer interface {
	mustEmbedUnimplementedScannerServer()
}

func RegisterScannerServer(s grpc.ServiceRegistrar, srv ScannerServer) {
	// If the following call panics, it indicates UnimplementedScannerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Scanner_ServiceDesc, srv)
}

func _Scanner_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scanner_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scanner_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scanner_Scan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServer).Scan(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Scanner_ServiceDesc is the grpc.ServiceDesc for Scanner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scanner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tgproxy.plugin.v1.Scanner",
	HandlerType: (*ScannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Scanner_Info_Handler,
		},
		{
			MethodName: "Scan",
			Handler:    _Scanner_Scan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	Redactor_Info_FullMethodName   = "/tgproxy.plugin.v1.Redactor/Info"
	Redactor_Redact_FullMethodName = "/tgproxy.plugin.v1.Redactor/Redact"
)

// RedactorClient is the client API for Redactor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Redactor is the service implemented by external redactor plugins.
type RedactorClient interface {
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error)
	Redact(ctx context.Context, in *RedactRequest, opts ...grpc.CallOption) (*RedactResponse, error)
}

type redactorClient struct {
	cc grpc.ClientConnInterface
}

func NewRedactorClient(cc grpc.ClientConnInterface) RedactorClient {
	return &redactorClient{cc}
}

func (c *redactorClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, Redactor_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redactorClient) Redact(ctx context.Context, in *RedactRequest, opts ...grpc.CallOption) (*RedactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedactResponse)
	err := c.cc.Invoke(ctx, Redactor_Redact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedactorServer is the server API for Redactor service.
// All implementations must embed UnimplementedRedactorServer
// for forward compatibility.
//
// Redactor is the service implemented by external redactor plugins.
type RedactorServer interface {
	Info(context.Context, *Empty) (*PluginInfo, error)
	Redact(context.Context, *RedactRequest) (*RedactResponse, error)
	mustEmbedUnimplementedRedactorServer()
}

// UnimplementedRedactorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRedactorServer struct{}

func (UnimplementedRedactorServer) Info(context.Context, *Empty) (*PluginInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedRedactorServer) Redact(context.Context, *RedactRequest) (*RedactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Redact not implemented")
}
func (UnimplementedRedactorServer) mustEmbedUnimplementedRedactorServer() {}
func (UnimplementedRedactorServer) testEmbeddedByValue()                  {}

// UnsafeRedactorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedactorServer will
// result in compilation errors.
type UnsafeRedactorServer interface {
	mustEmbedUnimplementedRedactorServer()
}

func RegisterRedactorServer(s grpc.ServiceRegistrar, srv RedactorServer) {
	// If the following call panics, it indicates UnimplementedRedactorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Redactor_ServiceDesc, srv)
}

func _Redactor_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedactorServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Redactor_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedactorServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Redactor_Redact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedactorServer).Redact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Redactor_Redact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedactorServer).Redact(ctx, req.(*RedactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Redactor_ServiceDesc is the grpc.ServiceDesc for Redactor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Redactor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tgproxy.plugin.v1.Redactor",
	HandlerType: (*RedactorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Redactor_Info_Handler,
		},
		{
			MethodName: "Redact",
			Handler:    _Redactor_Redact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
