// tg-proxy plugin protocol, v1.
//
// External scanners and redactors run as subprocesses spawned by tg-proxy
// via hashicorp/go-plugin and communicate over gRPC. This file is the
// single source of truth for what either side puts on the wire; the
// generated *.pb.go files alongside this proto, and the Python stubs under
// packaging/python-sdk-plugin/, are built from this one definition.
//
// Regenerate with:
//   make proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.0
// source: plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Direction tells a scanner whether the body is a client request or an
// upstream response. Matches api.Direction on the Go side.
type Direction int32

const (
	Direction_DIRECTION_REQUEST  Direction = 0
	Direction_DIRECTION_RESPONSE Direction = 1
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_REQUEST",
		1: "DIRECTION_RESPONSE",
	}
	Direction_value = map[string]int32{
		"DIRECTION_REQUEST":  0,
		"DIRECTION_RESPONSE": 1,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

// Severity matches api.Severity on the Go side.
type Severity int32

const (
	Severity_SEVERITY_INFO     Severity = 0
	Severity_SEVERITY_LOW      Severity = 1
	Severity_SEVERITY_MEDIUM   Severity = 2
	Severity_SEVERITY_HIGH     Severity = 3
	Severity_SEVERITY_CRITICAL Severity = 4
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_INFO",
		1: "SEVERITY_LOW",
		2: "SEVERITY_MEDIUM",
		3: "SEVERITY_HIGH",
		4: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_INFO":     0,
		"SEVERITY_LOW":      1,
		"SEVERITY_MEDIUM":   2,
		"SEVERITY_HIGH":     3,
		"SEVERITY_CRITICAL": 4,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

// Empty placeholder used by Info() RPCs that take no arguments.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

// Information about a plugin, returned by Info().
type PluginInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Hints carry metadata about the HTTP exchange.
type Hints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Direction     Direction              `protobuf:"varint,4,opt,name=direction,proto3,enum=tgproxy.plugin.v1.Direction" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hints) Reset() {
	*x = Hints{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hints) ProtoMessage() {}

func (x *Hints) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hints.ProtoReflect.Descriptor instead.
func (*Hints) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Hints) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Hints) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Hints) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Hints) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_REQUEST
}

// Finding is a single match reported by a scanner. start/end are byte
// offsets into the scanned slice; end is exclusive. Redactors rely on
// these offsets being precise — data[start:end] must equal the matched
// substring.
type Finding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Severity      Severity               `protobuf:"varint,2,opt,name=severity,proto3,enum=tgproxy.plugin.v1.Severity" json:"severity,omitempty"`
	Start         int32                  `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
	End           int32                  `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`
	Confidence    float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Scanner       string                 `protobuf:"bytes,6,opt,name=scanner,proto3" json:"scanner,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *Finding) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Finding) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_INFO
}

func (x *Finding) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Finding) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *Finding) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Finding) GetScanner() string {
	if x != nil {
		return x.Scanner
	}
	return ""
}

func (x *Finding) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Hints         *Hints                 `protobuf:"bytes,2,opt,name=hints,proto3" json:"hints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ScanRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ScanRequest) GetHints() *Hints {
	if x != nil {
		return x.Hints
	}
	return nil
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Findings      []*Finding             `protobuf:"bytes,1,rep,name=findings,proto3" json:"findings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ScanResponse) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

type RedactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Findings      []*Finding             `protobuf:"bytes,2,rep,name=findings,proto3" json:"findings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedactRequest) Reset() {
	*x = RedactRequest{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedactRequest) ProtoMessage() {}

func (x *RedactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedactRequest.ProtoReflect.Descriptor instead.
func (*RedactRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *RedactRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RedactRequest) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

type RedactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedactResponse) Reset() {
	*x = RedactResponse{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedactResponse) ProtoMessage() {}

func (x *RedactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedactResponse.ProtoReflect.Descriptor instead.
func (*RedactResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *RedactResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x11tgproxy.plugin.v1\"\a\n" +
	"\x05Empty\":\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x90\x01\n" +
	"\x05Hints\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12:\n" +
	"\tdirection\x18\x04 \x01(\x0e2\x1c.tgproxy.plugin.v1.DirectionR\tdirection\"\xbb\x02\n" +
	"\aFinding\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x127\n" +
	"\bseverity\x18\x02 \x01(\x0e2\x1b.tgproxy.plugin.v1.SeverityR\bseverity\x12\x14\n" +
	"\x05start\x18\x03 \x01(\x05R\x05start\x12\x10\n" +
	"\x03end\x18\x04 \x01(\x05R\x03end\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\x12\x18\n" +
	"\ascanner\x18\x06 \x01(\tR\ascanner\x12D\n" +
	"\bmetadata\x18\a \x03(\v2(.tgproxy.plugin.v1.Finding.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\vScanRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12.\n" +
	"\x05hints\x18\x02 \x01(\v2\x18.tgproxy.plugin.v1.HintsR\x05hints\"F\n" +
	"\fScanResponse\x126\n" +
	"\bfindings\x18\x01 \x03(\v2\x1a.tgproxy.plugin.v1.FindingR\bfindings\"[\n" +
	"\rRedactRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x126\n" +
	"\bfindings\x18\x02 \x03(\v2\x1a.tgproxy.plugin.v1.FindingR\bfindings\"$\n" +
	"\x0eRedactResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data*:\n" +
	"\tDirection\x12\x15\n" +
	"\x11DIRECTION_REQUEST\x10\x00\x12\x16\n" +
	"\x12DIRECTION_RESPONSE\x10\x01*n\n" +
	"\bSeverity\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x00\x12\x10\n" +
	"\fSEVERITY_LOW\x10\x01\x12\x13\n" +
	"\x0fSEVERITY_MEDIUM\x10\x02\x12\x11\n" +
	"\rSEVERITY_HIGH\x10\x03\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x042\x93\x01\n" +
	"\aScanner\x12?\n" +
	"\x04Info\x12\x18.tgproxy.plugin.v1.Empty\x1a\x1d.tgproxy.plugin.v1.PluginInfo\x12G\n" +
	"\x04Scan\x12\x1e.tgproxy.plugin.v1.ScanRequest\x1a\x1f.tgproxy.plugin.v1.ScanResponse2\x9a\x01\n" +
	"\bRedactor\x12?\n" +
	"\x04Info\x12\x18.tgproxy.plugin.v1.Empty\x1a\x1d.tgproxy.plugin.v1.PluginInfo\x12M\n" +
	"\x06Redact\x12 .tgproxy.plugin.v1.RedactRequest\x1a!.tgproxy.plugin.v1.RedactResponseB8Z6github.com/TensorGreed/tg-proxy/pkg/plugin/proto;protob\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_plugin_proto_goTypes = []any{
	(Direction)(0),         // 0: tgproxy.plugin.v1.Direction
	(Severity)(0),          // 1: tgproxy.plugin.v1.Severity
	(*Empty)(nil),          // 2: tgproxy.plugin.v1.Empty
	(*PluginInfo)(nil),     // 3: tgproxy.plugin.v1.PluginInfo
	(*Hints)(nil),          // 4: tgproxy.plugin.v1.Hints
	(*Finding)(nil),        // 5: tgproxy.plugin.v1.Finding
	(*ScanRequest)(nil),    // 6: tgproxy.plugin.v1.ScanRequest
	(*ScanResponse)(nil),   // 7: tgproxy.plugin.v1.ScanResponse
	(*RedactRequest)(nil),  // 8: tgproxy.plugin.v1.RedactRequest
	(*RedactResponse)(nil), // 9: tgproxy.plugin.v1.RedactResponse
	nil,                    // 10: tgproxy.plugin.v1.Finding.MetadataEntry
}
var file_plugin_proto_depIdxs = []int32{
	0,  // 0: tgproxy.plugin.v1.Hints.direction:type_name -> tgproxy.plugin.v1.Direction
	1,  // 1: tgproxy.plugin.v1.Finding.severity:type_name -> tgproxy.plugin.v1.Severity
	10, // 2: tgproxy.plugin.v1.Finding.metadata:type_name -> tgproxy.plugin.v1.Finding.MetadataEntry
	4,  // 3: tgproxy.plugin.v1.ScanRequest.hints:type_name -> tgproxy.plugin.v1.Hints
	5,  // 4: tgproxy.plugin.v1.ScanResponse.findings:type_name -> tgproxy.plugin.v1.Finding
	5,  // 5: tgproxy.plugin.v1.RedactRequest.findings:type_name -> tgproxy.plugin.v1.Finding
	2,  // 6: tgproxy.plugin.v1.Scanner.Info:input_type -> tgproxy.plugin.v1.Empty
	6,  // 7: tgproxy.plugin.v1.Scanner.Scan:input_type -> tgproxy.plugin.v1.ScanRequest
	2,  // 8: tgproxy.plugin.v1.Redactor.Info:input_type -> tgproxy.plugin.v1.Empty
	8,  // 9: tgproxy.plugin.v1.Redactor.Redact:input_type -> tgproxy.plugin.v1.RedactRequest
	3,  // 10: tgproxy.plugin.v1.Scanner.Info:output_type -> tgproxy.plugin.v1.PluginInfo
	7,  // 11: tgproxy.plugin.v1.Scanner.Scan:output_type -> tgproxy.plugin.v1.ScanResponse
	3,  // 12: tgproxy.plugin.v1.Redactor.Info:output_type -> tgproxy.plugin.v1.PluginInfo
	9,  // 13: tgproxy.plugin.v1.Redactor.Redact:output_type -> tgproxy.plugin.v1.RedactResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
